spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/db
    username: user
    password: passwordd
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect